services:
  # Serviço de autenticação
  auth-service:
    image: auth-service:latest
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/user-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_DATABASE=postgresql
      - SPRING_DATASOURCE_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    depends_on:
      - db
      - rabbitmq
      - zipkin
    restart: unless-stopped

  # Serviço de usuários
  user-service:
   image: user-service:latest
   container_name: user-service
   environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/user-db
     - SPRING_DATASOURCE_USERNAME=postgres
     - SPRING_DATASOURCE_PASSWORD=root
     - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
     - SPRING_JPA_SHOW_SQL=true
     - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
     - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
     - SPRING_DATASOURCE_DATABASE=postgresql
     - SPRING_DATASOURCE_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
     - CORS_ALLOWED_ORIGINS=http://localhost:3000
   ports:
     - "8081:8081"
   depends_on:
     - db
     - rabbitmq
     - zipkin
   restart: unless-stopped

  # Serviço de postagens
  post-service:
    image: post-service:latest
    container_name: post-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/user-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_DATABASE=postgresql
      - SPRING_DATASOURCE_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    ports:
      - "8083:8083"
    depends_on:
      - db
      - rabbitmq
      - zipkin
    restart: unless-stopped

  # Serviço de comentários
  comment-service:
    image: comment-service:latest
    container_name: comment-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/user-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_DATABASE=postgresql
      - SPRING_DATASOURCE_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    ports:
      - "8084:8084"
    depends_on:
      - db
      - rabbitmq
      - zipkin
    restart: unless-stopped

  # Serviço de auditoria
  audit-service:
   image: audit-service:latest
   container_name: audit-service
   environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/user-db
     - SPRING_DATASOURCE_USERNAME=postgres
     - SPRING_DATASOURCE_PASSWORD=root
     - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
     - SPRING_JPA_SHOW_SQL=true
     - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
     - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
     - SPRING_DATASOURCE_DATABASE=postgresql
     - SPRING_DATASOURCE_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
   ports:
     - "8082:8082"
   depends_on:
     - db
     - rabbitmq
     - zipkin
   restart: unless-stopped

  # RabbitMQ
  rabbitmq:
    image: "rabbitmq:3.8.6-management"
    container_name: rabbitmq-audit-service
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped

  # PostgreSQL
  db:
    image: postgres:13
    container_name: postgres_blog_user_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=user-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Zipkin (monitoramento)
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "9090:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: unless-stopped

volumes:
  postgres_data: