name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: user-db

      rabbitmq:
        image: rabbitmq:3.8.6-management
        ports:
          - 5672:5672
          - 15672:15672

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (optional for multi-arch builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (if you want to push the images to Docker Hub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker images for each service
      - name: Build auth-service image
        run: |
          docker build -t auth-service:latest ./auth-service

      - name: Build user-service image
        run: |
          docker build -t user-service:latest ./user-service

      - name: Build post-service image
        run: |
          docker build -t post-service:latest ./post-service

      - name: Build comment-service image
        run: |
          docker build -t comment-service:latest ./comment-service

      - name: Build audit-service image
        run: |
          docker build -t audit-service:latest ./audit-service
